from PyQt5 import QtCore, QtGui, QtWidgets


try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)

except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)


class Ui_everossgui(object):
    def setupUi(self, everossgui):
        everossgui.setObjectName("everossgui")
        everossgui.resize(810, 527)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        everossgui.setWindowIcon(icon)
        everossgui.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(everossgui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.maintabs = QtWidgets.QTabWidget(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.maintabs.setPalette(palette)
        self.maintabs.setAutoFillBackground(False)
        self.maintabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.maintabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.maintabs.setIconSize(QtCore.QSize(20, 20))
        self.maintabs.setElideMode(QtCore.Qt.ElideNone)
        self.maintabs.setUsesScrollButtons(True)
        self.maintabs.setDocumentMode(True)
        self.maintabs.setTabsClosable(False)
        self.maintabs.setMovable(True)
        self.maintabs.setObjectName("maintabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.keyEdit = QtWidgets.QLineEdit(self.tab_3)
        self.keyEdit.setObjectName("keyEdit")
        self.horizontalLayout_6.addWidget(self.keyEdit)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.activate = QtWidgets.QPushButton(self.tab_3)
        self.activate.setObjectName("activate")
        self.horizontalLayout_8.addWidget(self.activate)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.maintabs.addTab(self.tab_3, "")
        self.result = QtWidgets.QWidget()
        self.result.setObjectName("result")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.result)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.result)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.keyword = QtWidgets.QLineEdit(self.frame)
        self.keyword.setObjectName("keyword")
        self.horizontalLayout_2.addWidget(self.keyword)
        self.datequ = QtWidgets.QRadioButton(self.frame)
        self.datequ.setEnabled(True)
        self.datequ.setText("")
        self.datequ.setObjectName("datequ")
        self.horizontalLayout_2.addWidget(self.datequ)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.fromdate = QtWidgets.QDateEdit(self.frame)
        self.fromdate.setEnabled(False)
        self.fromdate.setDate(QtCore.QDate(2017, 3, 3))
        self.fromdate.setCalendarPopup(True)
        self.fromdate.setObjectName("fromdate")
        self.horizontalLayout_2.addWidget(self.fromdate)
        self.go = QtWidgets.QPushButton(self.frame)
        self.go.setObjectName("go")
        self.horizontalLayout_2.addWidget(self.go)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.resultscreen = QtWidgets.QTextBrowser(self.frame)
        self.resultscreen.setOpenExternalLinks(True)
        self.resultscreen.setObjectName("resultscreen")
        self.verticalLayout_10.addWidget(self.resultscreen)
        self.verticalLayout_3.addWidget(self.frame)
        self.maintabs.addTab(self.result, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.keyword_2 = QtWidgets.QLineEdit(self.tab_4)
        self.keyword_2.setObjectName("keyword_2")
        self.horizontalLayout_9.addWidget(self.keyword_2)
        self.go_2 = QtWidgets.QPushButton(self.tab_4)
        self.go_2.setObjectName("go_2")
        self.horizontalLayout_9.addWidget(self.go_2)
        self.clearBtn_2 = QtWidgets.QPushButton(self.tab_4)
        self.clearBtn_2.setEnabled(False)
        self.clearBtn_2.setObjectName("clearBtn_2")
        self.horizontalLayout_9.addWidget(self.clearBtn_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.resultscreen_2 = QtWidgets.QTextBrowser(self.tab_4)
        self.resultscreen_2.setOpenExternalLinks(True)
        self.resultscreen_2.setObjectName("resultscreen_2")
        self.verticalLayout_13.addWidget(self.resultscreen_2)
        self.maintabs.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(171, 171, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(171, 171, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.label_2.setPalette(palette)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtWidgets.QToolBox(self.frame_5)
        self.toolBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setObjectName("toolBox")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 98, 38))
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Noti_kwrd = QtWidgets.QLineEdit(self.page)
        self.Noti_kwrd.setAutoFillBackground(False)
        self.Noti_kwrd.setObjectName("Noti_kwrd")
        self.verticalLayout_9.addWidget(self.Noti_kwrd)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 313, 212))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.webhook_combo = QtWidgets.QComboBox(self.page_2)
        self.webhook_combo.setObjectName("webhook_combo")
        self.webhook_combo.addItem("")
        self.webhook_combo.addItem("")
        self.horizontalLayout_10.addWidget(self.webhook_combo)
        self.twit_usr = QtWidgets.QLineEdit(self.page_2)
        self.twit_usr.setObjectName("twit_usr")
        self.horizontalLayout_10.addWidget(self.twit_usr)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 98, 70))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Noti_On = QtWidgets.QPushButton(self.page_3)
        self.Noti_On.setObjectName("Noti_On")
        self.verticalLayout_7.addWidget(self.Noti_On)
        self.Noti_OFF = QtWidgets.QPushButton(self.page_3)
        self.Noti_OFF.setEnabled(False)
        self.Noti_OFF.setObjectName("Noti_OFF")
        self.verticalLayout_7.addWidget(self.Noti_OFF)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.maintabs.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stdo = QtWidgets.QTextBrowser(self.tab)
        self.stdo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.stdo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stdo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.stdo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stdo.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.stdo.setAcceptRichText(False)
        self.stdo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.stdo.setOpenExternalLinks(True)
        self.stdo.setObjectName("stdo")
        self.verticalLayout_4.addWidget(self.stdo)
        self.maintabs.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.maintabs)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.updatedbbtn = QtWidgets.QPushButton(self.groupBox_2)
        self.updatedbbtn.setObjectName("updatedbbtn")
        self.horizontalLayout_3.addWidget(self.updatedbbtn)
        #self.resett = QtWidgets.QPushButton(self.groupBox_2)
        #self.resett.setObjectName("resett")
        #self.horizontalLayout_3.addWidget(self.resett)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.exitbtn = QtWidgets.QPushButton(self.groupBox_2)
        self.exitbtn.setObjectName("exitbtn")
        self.horizontalLayout_3.addWidget(self.exitbtn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox)
        everossgui.setCentralWidget(self.centralwidget)
        self.actionSave_links = QtWidgets.QAction(everossgui)
        self.actionSave_links.setObjectName("actionSave_links")
        self.actionNew_search = QtWidgets.QAction(everossgui)
        self.actionNew_search.setObjectName("actionNew_search")
        self.actionQuit = QtWidgets.QAction(everossgui)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAdd_edit = QtWidgets.QAction(everossgui)
        self.actionAdd_edit.setObjectName("actionAdd_edit")
        self.actionLoad_proxies = QtWidgets.QAction(everossgui)
        self.actionLoad_proxies.setObjectName("actionLoad_proxies")
        self.actionPreferences = QtWidgets.QAction(everossgui)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(everossgui)
        self.actionAbout.setObjectName("actionAbout")
        self.actionProxies = QtWidgets.QAction(everossgui)
        self.actionProxies.setObjectName("actionProxies")
        self.actionProxies_2 = QtWidgets.QAction(everossgui)
        self.actionProxies_2.setObjectName("actionProxies_2")
        self.actionHelp = QtWidgets.QAction(everossgui)
        self.actionHelp.setObjectName("actionHelp")
        self.retranslateUi(everossgui)
        self.maintabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(everossgui)

    def retranslateUi(self, everossgui):
        everossgui.setWindowTitle(_translate("everossgui", "EVE Robotics Scraper X", None))
        self.label_4.setText(_translate("everossgui",
                                        "Welcome to EVE Robotics Scraper X Please enter your registration Key here and activate your copy ",
                                        None))
        self.keyEdit.setPlaceholderText(_translate("everossgui", "Registration Key", None))
        self.activate.setText(_translate("everossgui", "Activate", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_3), _translate("everossgui", "Welcome :", None))
        self.label.setText(_translate("everossgui", "Keyword :", None))
        self.label_3.setText(_translate("everossgui", "ON", None))
        self.fromdate.setDisplayFormat(_translate("everossgui", "yyyy-MM-dd", None))
        self.go.setText(_translate("everossgui", "Go", None))
        self.resultscreen.setHtml(_translate("everossgui",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                             "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>",
                                             None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.result), _translate("everossgui", "Search :", None))
        self.label_7.setText(_translate("everossgui", "Keyword :", None))
        self.go_2.setText(_translate("everossgui", "Start monitoring", None))
        self.clearBtn_2.setText(_translate("everossgui", "Stop", None))
        self.resultscreen_2.setHtml(_translate("everossgui",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>",
                                               None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_4), _translate("everossgui", "Monitor :", None))
        self.groupBox_3.setTitle(_translate("everossgui", "About NotiFier", None))
        self.label_2.setText(_translate("everossgui", "<html><head/><body><p><span style=\" font-size:10pt;\n"
                                                      "                              font-weight:600;\">NotiFier :</span></p><p>This part of EVE\n"
                                                      "                              Robotics Scraper X enables you to save a</p><p>Search phrase and Notify You\n"
                                                      "                              when new Products are</p><p>put online Via pushbullet.com Cross devices\n"
                                                      "                              notification</p><p>set up all your devices and enter your pushbullet access\n"
                                                      "                              token here </p></body></html>\n"
                                                      "                          ", None))
        self.groupBox_4.setTitle(_translate("everossgui", "NotiFier Configuration", None))
        self.Noti_kwrd.setPlaceholderText(_translate("everossgui", "Search phrase ", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("everossgui", "Search phrase", None))
        self.label_6.setText(
            _translate("everossgui", "Here you can inter slack /discord webhook to use them for notifications", None))
        self.webhook_combo.setItemText(0, _translate("everossgui", "Slack", None))
        self.webhook_combo.setItemText(1, _translate("everossgui", "Discord", None))
        self.twit_usr.setPlaceholderText(_translate("everossgui", "Incoming Webhook", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("everossgui", "Webhook", None))
        self.Noti_On.setText(_translate("everossgui", "ON", None))
        self.Noti_OFF.setText(_translate("everossgui", "OFF", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("everossgui", "On/OFF", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab_2), _translate("everossgui", "Notifier :", None))
        self.maintabs.setTabText(self.maintabs.indexOf(self.tab), _translate("everossgui", "Console", None))
        self.label_5.setText(_translate("everossgui", "Live :", None))
        self.updatedbbtn.setText(_translate("everossgui", "ON", None))
        #self.resett.setText(_translate("everossgui", "Reset Data", None))
        self.exitbtn.setText(_translate("everossgui", "Exit", None))
        self.actionSave_links.setText(_translate("everossgui", "Save ...", None))
        self.actionNew_search.setText(_translate("everossgui", "New Search", None))
        self.actionQuit.setText(_translate("everossgui", "Quit", None))
        self.actionAdd_edit.setText(_translate("everossgui", "add/edit", None))
        self.actionLoad_proxies.setText(_translate("everossgui", "Load proxies", None))
        self.actionPreferences.setText(_translate("everossgui", "Preferences ", None))
        self.actionAbout.setText(_translate("everossgui", "About", None))
        self.actionProxies.setText(_translate("everossgui", "Proxies ...", None))
        self.actionProxies_2.setText(_translate("everossgui", "Proxies ...", None))
        self.actionHelp.setText(_translate("everossgui", "Help", None))
